In [2]:
!pip install selenium

  Using cached selenium-3.141.0-py2.py3-none-any.whl (904 kB)


In [8]:
from selenium import webdriver 

driver = webdriver.Chrome("chromedriver") 
driver.implicitly_wait(3)
driver.get("https://www.danawa.com/") 

login = driver.find_element_by_css_selector('li.my_page_service > a')
print("HTML 요소: ", login)
print("태그 이름: ", login.tag_name)
print("문자열: ", login.text)
print("href 속성: ", login.get_attribute('href'))

login.click()
driver.implicitly_wait(3)

my_id = "love1770"
my_pw = "m9252009$$"

driver.find_element_by_id('danawa-member-login-input-id').send_keys(my_id)
driver.implicitly_wait(2)
driver.find_element_by_name('password').send_keys(my_pw)
driver.implicitly_wait(2)
driver.find_element_by_css_selector('button.btn_login').click()


HTML 요소:  <selenium.webdriver.remote.webelement.WebElement (session="906b30988a6d097570e607c64bd838be", element="82c34793-bb52-4807-bd05-807db7610240")>
태그 이름:  a
문자열:  로그인
href 속성:  https://auth.danawa.com/login?url=http%3A%2F%2Fwww.danawa.com%2F


In [13]:
from selenium import webdriver 

driver = webdriver.Chrome("chromedriver") 
driver.implicitly_wait(3)
driver.get("https://www.danawa.com/") 

login = driver.find_element_by_css_selector('li.my_page_service > a')
print("HTML 요소: ", login)
print("태그 이름: ", login.tag_name)
print("문자열: ", login.text)
print("href 속성: ", login.get_attribute('href'))

login.click()
driver.implicitly_wait(3)

my_id = "love1770"
my_pw = "m9252009$$"

driver.find_element_by_id('danawa-member-login-input-id').send_keys(my_id)
driver.implicitly_wait(2)
driver.find_element_by_name('password').send_keys(my_pw)
driver.implicitly_wait(2)
driver.find_element_by_css_selector('button.btn_login').click()
driver.implicitly_wait(2)
wishlist = driver.find_element_by_css_selector('li.interest_goods_service > a').click()
driver.implicitly_wait(2)
html_src = driver.page_source
driver.close()
# print(html_src[:])

from bs4 import BeautifulSoup
import re
soup = BeautifulSoup(html_src, 'html.parser')

wish_table = soup.select('table[class="tbl wish_tbl"]')[0]
wish_items = wish_table.select('tbody tr')

for item in wish_items:
    title = item.find('div', {'class':'tit'}).text
    price = item.find('span', {'class':'price'}).text
    link = item.find('a', href=re.compile('prod.danawa.com/info/')).get('href')
    print(title)
    print(price)
    print(link)
    print("\n")



HTML 요소:  <selenium.webdriver.remote.webelement.WebElement (session="bd4821fd1ea1aff9d359528b9bf677af", element="688c886a-9c82-4bb6-8c4c-dd9c8783dba6")>
태그 이름:  a
문자열:  로그인
href 속성:  https://auth.danawa.com/login?url=http%3A%2F%2Fwww.danawa.com%2F
APPLE 2020 맥북에어 MGN93KH/A (8GB, SSD 256GB)

1,164,890원
							
http://prod.danawa.com/info/?pcode=12660506


APPLE 2020 맥북에어 MGN63KH/A (8GB, SSD 256GB)

1,158,720원
							
http://prod.danawa.com/info/?pcode=12660491


COLORFUL iGAME 지포스 RTX 3070 Ultra OC D6 8GB White

1,599,780원
							
http://prod.danawa.com/info/?pcode=12613199


이엠텍 지포스 GTX 1660 SUPER STORM X Dual OC D6 6GB

880,000원
							
http://prod.danawa.com/info/?pcode=9790980


삼성전자 970 EVO M.2 NVMe (500GB)

107,000원
							
http://prod.danawa.com/info/?pcode=6095784


삼성전자 860 EVO (500GB)

78,810원
							
http://prod.danawa.com/info/?pcode=5834210




In [14]:
from selenium import webdriver 
import time

def download_bok_statistics():

    driver = webdriver.Chrome("chromedriver") 
    driver.implicitly_wait(3)
    driver.get("http://ecos.bok.or.kr/jsp/vis/keystat/#/key") 
    
    
    excel_download = driver.find_element_by_css_selector('img[alt="download"]')
    driver.implicitly_wait(3)
    
    excel_download.click()
    time.sleep(5)
    
    driver.close()
    print("파일 다운로드 실행...")

    return None

download_bok_statistics()

파일 다운로드 실행...


In [15]:
from selenium import webdriver 
from bs4 import BeautifulSoup
import time

def download_bok_statistics_by_keyword():
    
    item_found = 0              
    while not item_found:
        
        keyword = ""       
        while len(keyword) == 0:
            keyword = str(input("검색할 항목을 입력하세요: "))
        
        driver = webdriver.Chrome("chromedriver")
        driver.implicitly_wait(3)
        driver.get("http://ecos.bok.or.kr/jsp/vis/keystat/#/key") 
        time.sleep(5)             
                   
        items1 = driver.find_elements_by_css_selector('a[class="ng-binding"]')
        items2 = driver.find_elements_by_css_selector('a[class="a-c1-list ng-binding"]')
        items3 = driver.find_elements_by_css_selector('a[class="a-c4-list ng-binding"]')
        driver.implicitly_wait(3)

        items = items1[1:] + items2 + items3 

        for idx, item in enumerate(items):
            if keyword in item.text:
                print("검색어 '%s'에 매칭되는 '%s' 통계지표를 검색 중..." % (keyword, item.text))
                item.click()
                item_found = 1
                time.sleep(5)
                break
            elif idx == (len(items) - 1):
                print("검색어 '%s'에 대한 통계지표가 존재하지 않습니다..." % keyword)
                driver.close()
                continue
            else:
                pass
            
    html_src = driver.page_source
    soup = BeautifulSoup(html_src, 'html.parser')
    driver.close()
  
    table_items = soup.find_all('td', {'class':'ng-binding'})
    date = [t.text for i, t in enumerate(table_items) if i % 3 == 0]
    value = [t.text for i, t in enumerate(table_items) if i % 3 == 1]    
    change = [t.text for i, t in enumerate(table_items) if i % 3 == 2]    
    
    result_file = open('bok_statistics_%s.csv' % keyword, 'w')
    for i in range(len(date)):
        result_file.write("%s, %s, %s" % (date[i], value[i], change[i]))
        result_file.write('\n')
    
    result_file.close()
    print("키워드 '%s'에 대한 통계지표를 저장하였습니다." % keyword)
    
    return date, value, change

result = download_bok_statistics_by_keyword()
print(result)


검색할 항목을 입력하세요: CD
검색어 'CD'에 매칭되는 'CD수익률(91일) ('21.07.23)' 통계지표를 검색 중...
키워드 'CD'에 대한 통계지표를 저장하였습니다.
(['2014', '2015', '2016', '2017', '2018', '2019', '2020', '2020.12', '2021.1', '2021.2', '2021.3', '2021.4', '2021.5', '2021.6', '2021.7.16', '2021.7.19', '2021.7.20', '2021.7.21', '2021.7.22', '2021.7.23'], ['2.49', '1.76', '1.49', '1.44', '1.68', '1.69', '0.92', '0.66', '0.68', '0.73', '0.75', '0.74', '0.68', '0.66', '0.70', '0.70', '0.70', '0.70', '0.70', '0.70'], ['-0.23', '-0.73', '-0.27', '-0.05', '0.24', '0.01', '-0.77', '0.00', '0.02', '0.05', '0.02', '-0.01', '-0.06', '-0.02', '0.01', '0.00', '0.00', '0.00', '0.00', '0.00'])


## 넘파이

In [25]:
import numpy as np
 
list1 = [1, 2, 3, 4]
print(list1)
print(type(list1))
a = np.array(list1)
print(a)
print(type(a))
print(a.ndim)
print(a.shape) 
 
b = np.array([[1,2,3],[4,5,6]])
print(b.ndim)
print(b.shape)

print(b[1,2]) 


[1, 2, 3, 4]
<class 'list'>
[1 2 3 4]
<class 'numpy.ndarray'>
1
(4,)
2
(2, 3)
6


In [36]:
import numpy as np
 
# a = np.zeros((2,2))
# print(a)
 
# a = np.ones((2,3))
# print(a)
 
# a = np.full((2,3), 5)
# print(a)
 
# a = np.eye(3)
# print(a)
 
list(range(20))
np.array(range(20))
a = np.array(range(20)).reshape((4,5))
print(a)

a = a.reshape((2,10))
print(a)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [40]:
import numpy as np
 
lst = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

arr = np.array(lst)
print(arr.shape)
 
a = arr[0:2, 0:2] #  (2,2)
print(a)
print(a.shape)
 
a = arr[1:, 1:]
print(a)
print(a.shape)

(3, 3)
[[1 2]
 [4 5]]
(2, 2)
[[5 6]
 [8 9]]
(2, 2)


In [41]:
import numpy as np
 
lst = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]
a = np.array(lst)
 
s = a[[0, 2], [1, 3]]
 
print(s)

[ 2 12]


### 넘파이 인덱싱

In [46]:
a = np.array([1,2,3,4,5])
print(a.shape)
print( a[1] )
print( type(a[1]) )

print( a[[0,3]] )

(5,)
2
<class 'numpy.int32'>
[1 4]


### 넘파이 슬라이싱

In [45]:
a = np.array([1,2,3,4,5])
print(a.shape)
print( a[1:2] )
print( type(a[1:2]) )

(5,)
[2]
<class 'numpy.ndarray'>


### 넘파이 불린 인덱싱

In [47]:
a = np.array([1,2,3,4,5])
print( a[[True, False, True, False, True]] )

[1 3 5]


In [48]:
a[[True, False, True, False, True]] = 0
print(a)

[0 2 0 4 0]


In [49]:
a = np.array([1,-2,3,-4,5])

for i in range(5):
    if a[i] < 0 :
        a[i] = 0

print(a)

[1 0 3 0 5]


In [51]:
a = np.array([1,-2,3,-4,5])
mask = a < 0
print(mask)
a[mask] = 0
print(a)

[False  True False  True False]
[1 0 3 0 5]


In [52]:
a = np.array([[1,-2,3,-4,5],
              [-1,2,-3,4,-5]])
mask = a < 0
print(mask)
a[mask] = 0
print(a)

[[False  True False  True False]
 [ True False  True False  True]]
[[1 0 3 0 5]
 [0 2 0 4 0]]


In [53]:
import numpy as np
 
lst = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
a = np.array(lst)
 
bool_indexing_array = np.array([
    [False,  True, False],
    [True, False,  True],
    [False,  True, False]
])
 
n = a[bool_indexing_array];
print(n) 

[2 4 6 8]


In [55]:
import numpy as np
 
lst = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
a = np.array(lst)
 
bool_indexing = (a % 2 == 0)
print(bool_indexing)
print(a[bool_indexing])

n = a[ a % 2 == 0 ]
print(n)


[[False  True False]
 [ True False  True]
 [False  True False]]
[2 4 6 8]
[2 4 6 8]


In [68]:
import numpy as np
 
# a = [1,2,3]
# b = [4,5,6]
 
# c = a + b
# print(c)  
    
a = np.array([1,2,3])
b = np.array([4,5,6])
 
c = a + b
print(c)
 
c = a - b
print(c)
 
# c = np.multiply(a, b)
c = a * b
print(c)
 
# c = np.divide(a, b)
c = a / b
print(c)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


### 넘파이 브로드캐스팅

In [69]:
a = np.array([1,2,3,4,5])  # a.ndim=1  ,  a.shape=(5,)
b = np.array([3,3,3,3])    # b.ndim=1  ,  b.shape=(4,)
c = a + b
print(c)

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [79]:
import numpy as np

x = np.array([[1,2,3], 
              [4,5,6], 
              [7,8,9], 
              [10, 11, 12]])               # 2 (4, 3)  
v = np.array([1, 0, 1])   #   [[1, 0, 1],
                          #    [1, 0, 1],
                          #    [1, 0, 1],
                          #    [1, 0, 1]]    # 1 (3,) => (4,3)
            
y = x + v
print(y)
y = np.empty_like(x)   
# print(y)

for i in range(4):
    y[i, :] = x[i, :] + v

print(y)


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [81]:
import numpy as np

x = np.array([[1,2,3], 
              [4,5,6], 
              [7,8,9], 
              [10, 11, 12]])               
v = 3       #  () => (4, 3)
y = x + v
print(y)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [87]:
import numpy as np

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

# print(x+v)

vv = np.tile(v, (4, 1))  
print(vv)                 
y = x + vv  
print(y) 


[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [91]:
import numpy as np

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = 3 

# print(x+v)

vv = np.tile(v, (4, 3))  
print(vv)                 
y = x + vv  
print(y)

[[3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [101]:
import numpy as np

x = np.array([[1,2,3], 
              [4,5,6], 
              [7,8,9]])

v = np.array([1,0,1])
y = np.zeros(x.shape)
print(y)
# print(x.ndim)
# print(x.shape)
# print(x[0].shape)
# print(x[0])
# print(x[1, 1])

# for i in range(3):
#     print( x[i, :] )

for i in range(3):
    y[i, :] = x[i, :] + v
    
print(y)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 2.  2.  4.]
 [ 5.  5.  7.]
 [ 8.  8. 10.]]
