### 리스트 컴프리헨션

In [4]:
square = [ x**2 for x in range(10)]
print(square)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [5]:
combs = []
for x in [1,2,3]:
    for y in [3,1,4]:
        if x != y:
            combs.append((x, y))
print(combs)

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]


In [6]:
combs = [(x, y) for x in [1,2,3] for y in [3,1,4] if x != y]
print(combs)

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]


In [7]:
gugudan = [ x*y for x in [2,3] for y in range(1,10) ]
print(gugudan)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 3, 6, 9, 12, 15, 18, 21, 24, 27]


In [8]:
vec = [-4, -2, 0, 2, 4]
a = [x*2 for x in vec]
print(a)

[-8, -4, 0, 4, 8]


In [13]:
a = [ x for x in vec if x>=0]
print(a)

[0, 2, 4]


In [15]:
a = [ abs(x) for x in vec ]
print(a)

[4, 2, 0, 2, 4]


In [18]:
freshfruit = ['  banana', '  loganberry ', 'passion fruit  ']
a = [x.strip() for x in freshfruit]
print(a)

['banana', 'loganberry', 'passion fruit']


In [17]:
a = [(x, x**2) for x in range(6)]
print(a)

[(0, 0), (1, 1), (2, 4), (3, 9), (4, 16), (5, 25)]


In [24]:
a = (1,2)
print(type(a))
b = 1,2  # 튜플 패킹
print(type(b))
print(b)

<class 'tuple'>
<class 'tuple'>
(1, 2)


In [27]:
a = [(x, x**2) for x in range(6)]
print(a)

[(0, 0), (1, 1), (2, 4), (3, 9), (4, 16), (5, 25)]


In [28]:
vec = [[1,2,3], [4,5,6], [7,8,9]]
a = [num for elem in vec for num in elem]
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [33]:
matrix = [
             [1, 2, 3, 4],
             [5, 6, 7, 8],
             [9, 10, 11, 12],
         ]

In [30]:
a=[[row[i] for row in matrix] for i in range(4)]  #[[1,5,9],[2,6,10],[3,7,11],[4,8,12]]
print(a)

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]


In [31]:
transposed = []
for i in range(4):
    transposed.append([row[i] for row in matrix])
print(transposed)

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]


In [32]:
import numpy as np

matrix = np.array([
             [1, 2, 3, 4],
             [5, 6, 7, 8],
             [9, 10, 11, 12],
         ])

print(matrix.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [34]:
# [[row[i] for row in matrix] for i in range(4)] 

transposed = []
for i in range(4):
    transposed_row = []
    for row in matrix:
        transposed_row.append(row[i])
    transposed.append(transposed_row)

print(transposed)

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]


### 튜플 응용

In [38]:
t = 12345, 54321, 'hello!' # 튜플 패킹
print(t)
t[0]

(12345, 54321, 'hello!')


12345

In [39]:
u = t, (1, 2, 3, 4, 5)
print(u)

((12345, 54321, 'hello!'), (1, 2, 3, 4, 5))


In [40]:
t[0] = 88888

TypeError: 'tuple' object does not support item assignment

In [41]:
del t[0]

TypeError: 'tuple' object doesn't support item deletion

In [43]:
v = ([1, 2, 3], [3, 2, 1])
# v[0] = 2
v[0][0] = 2
v

([2, 2, 3], [3, 2, 1])

In [51]:
empty = ()
print(type(empty))

<class 'tuple'>


In [56]:
singleton = 'hello',
print(type(singleton))
print(singleton)

<class 'tuple'>
('hello',)


In [59]:
t = 1,2,3    # 튜플 패킹
x, y, z = t  # 튜플 언패킹
print(x,y,z)

1 2 3


In [60]:
x, y, z = 1,2,3
print(x,y,z)

1 2 3


In [61]:
a = 0
b = 1
while a < 10:
    print(a, end=' ')
    c = a+b
    a = b
    b = c

0 1 1 2 3 5 8 

In [62]:
a = 0
b = 1
while a < 10:
    print(a, end=' ')
    a, b = b, a+b

0 1 1 2 3 5 8 

In [63]:
a = 3
b = 4

t = a
a = b
b = t
print(a, b)

4 3


In [64]:
a = 3
b = 4

b,a = a,b
print(a, b)

4 3


In [67]:
import sys

print(type("a"))
print(sys.getsizeof("a"))

print(type("ab"))
print(sys.getsizeof("ab"))

<class 'str'>
50
<class 'str'>
51


### 문자열 함수

In [88]:
a = "hello hello world"
print(a)
print(len(a))
print(a.upper())
print(a.lower())
print(a.capitalize())
print(a.title())
print(a.count('wor'))
print(a.find("hel"))
print(a.rfind('hel'))
print(a.startswith('world'))
print(a.endswith('world'))

hello hello world
17
HELLO HELLO WORLD
hello hello world
Hello hello world
Hello Hello World
1
0
6
False
True


In [92]:
a = "   hello   "
print("["+a.strip()+"]")
print("["+a.rstrip()+"]")
print("["+a.lstrip()+"]")

[hello]
[   hello]
[hello   ]


In [94]:
a = input().split()
print(a)

12 23 34
['12', '23', '34']


In [95]:
a = "hello world how are you"
b = a.split()
print(b)

['hello', 'world', 'how', 'are', 'you']


In [97]:
hp = "010-1234-5678"
b = hp.split("-")
print(b)

['010', '1234', '5678']


In [99]:
ip = "192.168.56.1"
b = ip.split(".")
print(b)

['192', '168', '56', '1']


In [102]:
a = "1234"
if a.isdigit():
    print("숫자 : %d"%(int(a)))
else :
    print("숫자 아님")

숫자 : 1234


### 문자열 역 슬레쉬 

In [105]:
print('"Isn\'t," they said.')

"Isn't," they said.


In [110]:
s = 'First line.\nSecond line.'  
print(s)

First line.
Second line.


In [112]:
print('C:\some\\name')

C:\some\name


In [113]:
print(r'C:\some\name')

C:\some\name


In [116]:
print('''
Usage: thingy [OPTIONS]
     -h                        Display this usage message
     -H hostname               Hostname to connect to
''')



Usage: thingy [OPTIONS]
     -h                        Display this usage message
     -H hostname               Hostname to connect to



In [117]:
a = 'py'+'thon'
print(a)

python


In [118]:
a = 'py' 'thon'
print(a)

python


In [119]:
text = ('Put several strings within parentheses '
        'to have them joined together.')
text

'Put several strings within parentheses to have them joined together.'

In [121]:
prefix = 'Py'
prefix+'thon'

'Python'

In [124]:
('un' * 3)+'ium'

'unununium'

### 딕셔너리 출력

In [125]:
x = {'a': 10, 'b':20, 'c':30, 'd':40}
for i in x:
    print(i, end=' ')

a b c d 

In [126]:
x = {'a': 10, 'b':20, 'c':30, 'd':40}
for key, value in x.items():
    print(key, value)

a 10
b 20
c 30
d 40


In [127]:
x = {'a': 10, 'b':20, 'c':30, 'd':40}
for key in x.keys():
    print(key)

a
b
c
d


In [128]:
x = {'a': 10, 'b':20, 'c':30, 'd':40}
for key in x.values():
    print(key)

10
20
30
40


In [130]:
a = [1,2,3,4]
b = [5,6,7,8]
for i,j in zip(a,b):
    print(i,j)

1 5
2 6
3 7
4 8


In [132]:
a = [1,2,3,4]
for i,data in enumerate(a):
    print(i,data)

0 1
1 2
2 3
3 4


In [133]:
keys = ['a', 'b', 'c', 'd']
values = [10, 20, 30 ,40]
x = {key: value for key, value in zip(keys,values)}
x

{'a': 10, 'b': 20, 'c': 30, 'd': 40}

In [134]:
keys = ['a', 'b', 'c', 'd']
values = [10, 20, 30 ,40]
x = {}
for key, value in zip(keys,values):
    x[key] = value
x

{'a': 10, 'b': 20, 'c': 30, 'd': 40}

In [136]:
y = {value: key for key, value in x.items()}
y

{10: 'a', 20: 'b', 30: 'c', 40: 'd'}

In [137]:
encode = [20, 30, 40, 40, 10]
z = [y[i] for i in encode]
z

['b', 'c', 'd', 'd', 'a']

In [138]:
x = {'a': 10, 'b': 20, 'c': 30, 'd': 40}
x = {key: value for key, value in x.items() if value !=20 }
x

{'a': 10, 'c': 30, 'd': 40}

### 중첩된 딕셔너리

In [141]:
planet = {
    'Earth' : {
        'mean_radius' : 6371.0,
        'orbital_perioid' : 365.2422
    },
    'Mars' : {
        'mean_radius' : 3389.5,
        'orbital_perioid' : 686.9600
    }
}

In [142]:
print(planet)

{'Earth': {'mean_radius': 6371.0, 'orbital_perioid': 365.2422}, 'Mars': {'mean_radius': 3389.5, 'orbital_perioid': 686.96}}


In [143]:
print(planet['Earth'])

{'mean_radius': 6371.0, 'orbital_perioid': 365.2422}


In [144]:
print(planet['Earth']['mean_radius'])

6371.0


In [145]:
planet['Earth']['orbital_perioid'] = 365.25641

In [146]:
print(planet['Mars'])

{'mean_radius': 3389.5, 'orbital_perioid': 686.96}


In [149]:
x = {'a': 0, 'b': 0, 'c': 0, 'd': 0}
y = x
x is y
print(hex(id(x)))
print(hex(id(y)))

0x168fc656980
0x168fc656980


In [157]:
x = {'a': 0, 'b': 0, 'c': 0, 'd': 0}
print(hex(id(x)))
print(hex(id(x['a'])))
print(hex(id(x['b'])))
print(hex(id(x['c'])))
print(hex(id(x['d'])))
y = x
y['a'] = 99
print(hex(id(x)))
print(hex(id(x['a'])))
print(hex(id(x['b'])))
print(hex(id(x['c'])))
print(hex(id(x['d'])))

0x168fc63c700
0x7ffeea212710
0x7ffeea212710
0x7ffeea212710
0x7ffeea212710
0x168fc63c700
0x7ffeea213370
0x7ffeea212710
0x7ffeea212710
0x7ffeea212710


In [159]:
print(x['a'])
print(y['a'])

99
99


In [163]:
x = {'a': 0, 'b': 0, 'c': 0, 'd': 0}
print(hex(id(x)))
print(hex(id(x['a'])))
print(hex(id(x['b'])))
print(hex(id(x['c'])))
print(hex(id(x['d'])))
y = x.copy()
y['a'] = 99
print(hex(id(y)))
print(hex(id(y['a'])))
print(hex(id(y['b'])))
print(hex(id(y['c'])))
print(hex(id(y['d'])))
print(x['a'])
print(y['a'])

0x168fc664f00
0x7ffeea212710
0x7ffeea212710
0x7ffeea212710
0x7ffeea212710
0x168fc1a1900
0x7ffeea213370
0x7ffeea212710
0x7ffeea212710
0x7ffeea212710
0
99


In [164]:
x = {'a': {'python' : '2.7'}, 'b': {'python' : '3.8'}}
y = x.copy()
y['a']['python'] = '2.7.15'
print(x)
print(y)

{'a': {'python': '2.7.15'}, 'b': {'python': '3.8'}}
{'a': {'python': '2.7.15'}, 'b': {'python': '3.8'}}


In [165]:
import copy
x = {'a': {'python' : '2.7'}, 'b': {'python' : '3.8'}}
y = copy.deepcopy(x)
y['a']['python'] = '2.7.15'
print(x)
print(y)

{'a': {'python': '2.7'}, 'b': {'python': '3.8'}}
{'a': {'python': '2.7.15'}, 'b': {'python': '3.8'}}


### 집합 자료형

In [166]:
s =set([1,2,3,1,2,3])
print(s)

{1, 2, 3}


In [171]:
s.add(1)
print(s)

{1, 2, 3}


In [172]:
s.remove(1)   # 전달받은 값을 삭제 (없을 때 에러 메시지를 출력)
print(s)

{2, 3}


In [173]:
s.update([1,4,5,6,7])
print(s)

{1, 2, 3, 4, 5, 6, 7}


In [176]:
s.discard(3)  # 전달받은 값을 삭제 (없을 때 그냥 무시)
print(s)

{1, 2, 4, 5, 6, 7}


In [177]:
s.clear()
print(s)

set()


In [179]:
s1 =set([1,2,3,4,5])
s2 =set([3,4,5,6,7])
print(s1.union(s2)) # 합집합
print(s1 | s2)

{1, 2, 3, 4, 5, 6, 7}
{1, 2, 3, 4, 5, 6, 7}


In [180]:
print(s1.intersection(s2))
print(s1 & s2)

{3, 4, 5}
{3, 4, 5}


In [181]:
print(s1.difference(s2))
print(s1 - s2)

{1, 2}
{1, 2}


In [182]:
print(s2.difference(s1))
print(s2 - s1)

{6, 7}
{6, 7}


In [183]:
print(s1.symmetric_difference(s2))
print(s1 ^ s2)

{1, 2, 6, 7}
{1, 2, 6, 7}


In [184]:
a = {}
print(type(a))

<class 'dict'>


In [186]:
a = {i for i in 'apple'}
print(type(a))
print(a)

<class 'set'>
{'e', 'a', 'p', 'l'}


In [187]:
a = set()
print(type(a))

<class 'set'>


In [188]:
a = {i for i in 'pineapple' if i not in 'apl'}
a

{'e', 'i', 'n'}

In [203]:
corpus = "you say goodbye and i say hello ." 
words = corpus.split()
vocab = {x for x in words if x not in '.'}
vocab

{'and', 'goodbye', 'hello', 'i', 'say', 'you'}

In [204]:
a = {4,3,5,2,6,1}
for i in a:
    print(i, end=" ")

1 2 3 4 5 6 

### 연습문제 1번

In [207]:
a = ['alpha', 'bravo', 'Charlie', 'delta', 'echo', 'foxtrot']
for i, data in enumerate(a):
    if len(data) == 5:
        a[i] = a[i].upper()
print(a)

['ALPHA', 'BRAVO', 'Charlie', 'DELTA', 'echo', 'foxtrot']


In [210]:
a = ['alpha', 'bravo', 'Charlie', 'delta', 'echo', 'foxtrot']
b = [ i.upper() if len(i)==5 else i  for i in a ]
print(b)

['ALPHA', 'BRAVO', 'Charlie', 'DELTA', 'echo', 'foxtrot']
